### ISSUE TITLE
we should set vue to production mode in our production build

### ISSUE THREAD

**Issue by balmas** [alpheios-project/node-build#11]
The released version of the embedded library has vue in development mode. Not sure if we have this switch enabled in our node-build already and if it's something I missed with the embed-lib build, or if we need to add it.  Making a note so we address with the MVP release.

https://vuejs.org/v2/guide/deployment.html

**Comment by balmas** [comment]
@kirlat can you take a look at this one too before you move on to the Safari Auth work?

**Comment by kirlat** [comment]
Yes, I will

**Comment by kirlat** [comment]
I did not find any direct way to verify it (if not to count that there is no development mode warning from Vue.js in the console), but it seems that our webpack configuration already takes care of that. We're using `produciton` and `development` modes for the respective builds, and this triggers corresponding modes in Vue.js: https://vuejs.org/v2/guide/deployment.html#With-Build-Tools

**Comment by balmas** [comment]
hmm. then why do we get this in the console?

![AwesomeScreenshot-Screenshot-from-2019-07-10-13-06-57-2019-07-10-13-07-49](https://user-images.githubusercontent.com/644870/60989377-daad3000-a313-11e9-990e-31840d4565bb.png)

**Comment by kirlat** [comment]
This has been fixed and all necessary changes has been merged into master branches of corresponding packages (node-build, components, webextension).

**Comment by balmas** [comment]
this is in qa-3.0.0.46/embed-lib-1.0.0.28 (with components 1.2.2)

Test by confirming the notice is gone from the developer console.

**Comment by monzug** [comment]
yes! I did not get the note from the developer console. tested in embed-lib-1.0.0.28 (with components 1.2.2)

**Comment by monzug** [comment]
and qa-3.0.0.46
