### ISSUE TITLE
eslint 5.0 is incompatible with StandardJS

### ISSUE THREAD

**Issue by balmas** [alpheios-project/node-build#7]
See https://github.com/standard/standard/issues/1163

I cleared out my node_modules folder for the embed-lib and couldn't get the standard --fix command to work anymore.

**Comment by kirlat** [comment]
@balmas, what would be the best way to reproduce this? Is this problem Atom-specific? I'm using IntelliJ IDEA and I've seen this error a month or two before, but now it's gone away. I'm under impression that an update to the latest eslint/standard versions somehow fixed that, but I might be wrong and there might be a fix on IntelliJ side.

Would love to try to fix this, if possible.

**Comment by balmas** [comment]
This was not an issue with Atom, but I have no idea what the source of the problem was. I wonder if it might have to do with the order in which certain dependencies are installed. With a clean clone of the repository I am not able to reproduce it now.

Agree with comments in PR #8 that we need to reduce the duplicate dependencies across the Alpheios repositories so that we can better isolate dependency problems going forward.  Will review the different libraries and submit issues on each individual repository as needed for this.
