### ISSUE TITLE
add eslint-plugin-vue

### ISSUE THREAD

**Issue by balmas** [alpheios-project/node-build#9]
we should add eslint-plugin-vue to our build library for standardized use across repositories

**Comment by kirlat** [comment]
I'm not sure we can add this to the build library, unfortunately (at least I don't see a way to do it right now except for implementing a linter command wrapper within a build library which can be time consuming). `node-build` is running Webpack builds with pre-defined build configurations. `eslint-plugin-vue` is a plugin for eslint/standard and it should be installed and configured on a host package level along with standard itself. 

Luckily, we do not have too many packages with Vue components. Their package config files should be easy to update.

**Comment by balmas** [comment]
ok. let's just do wit whatever way is easiest then. I'll close this as an issue and just make it a task on the project then.

**Comment by balmas** [comment]
actually we probably only need it on components for now...
